# Discord bot token
bot-token: "YOUR_BOT_TOKEN_HERE"

# Roles allowed to execute commands from Discord
allowed-roles:
  - "Admin"
  - "Moderator"

# Channel where Minecraft ↔ Discord logs are sent
log-channel-id: "123456789012345678"
