name: DiscordIncorporation
version: 1.0
main: di.zsanchez31.discordincorporation.DiscordIncorporation
api-version: 1.17

author: YourName
description: "Plugin to integrate Discord with Minecraft, bidirectional chat, remote commands, and logs."

commands:
  discordinc:
    description: "Main plugin command"
    usage: "/discordinc reload"
    aliases: [di, dic]
